on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.2.2
      - name: Uplaod ftp
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{secrets.FTP_HOST}}
          user: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          localDir: .
          remoteDir: /www/wwwroot/wuxian.space
